name: Godot testing
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:
jobs:
  testing:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Run unit tests
        uses: croconut/godot-tester@v5.1
        with:
          # required
          version: "4.1"